### ISSUE TITLE
Per-zone provider-specific settings

### ISSUE THREAD

**Issue by jleroy** [github/octodns#1254]
I'm working on a custom provider for Bunny DNS.
They allow to set the zone root NS records only in zone settings, not by updating records.

Is there a way to store and access per-zone provider-specific settings? Like what the Cloudflare module does but on zone level instead of record-level.
I want to do something like that:

```yaml
example.com.:
  bunny:
    custom_ns1: ns1.example.com.
    custom_ns2: ns2.example.com.
sources:
  - config_yaml
targets:
  - bunny
```

Thanks!
