### ISSUE TITLE
Long TXT Record handling across providers

### ISSUE THREAD

**Issue by yzguy** [github/octodns#127]
Hello,

We currently use Dyn + NSOne for DNS, recently we added a new TXT record for DKIM that was quite long. According to https://kb.isc.org/article/AA-00356/0/Can-I-have-a-TXT-or-SPF-record-longer-than-255-characters.html, we would just split the value, wrap in quotes, put a space between.

This works fine for Dynect, after submitting they auto-escape it. However, as we've seen other times with NSOne they don't particularly follow RFC all the time, or they provide some convenience through their API/UI. For me to put the same record in NSOne I just put the long value, no escaping, no breaking up, no quoting.

Now with OctoDNS after dumping the zone from NSOne, it wants to change Dyn's record to match. This would remove the quotes, space, etc. If it were applied, you get a txtdata: Too long error back from Dynect.

If you use dig to query for the record against both providers, you receive the same response.

NSOne
```
google._domainkey:
  type: TXT
  value: v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnvUZ3wn3GvTx413NLq0PViwC1w7TZubYyipPswsyECqii1xxmDtSZjSTWq2iYU3FBeyii6wNS4yl0JQ4kS286Sbe1LWCr7ovS5KTEZgu/gVK4A07nKKKXOjmTXuTMqwsTMnYCvwkhACANXzuhE3ArhChPEOFzhAF+2waLgQ8/pBPtEXG49g+aXjfwkbRmxmlavjQKwM9gQhEPL+drfU0CwQa4X/BVMq6JTcPW73UPZfQPtqjKbxW6hJQ1tOFLj2fV/lFL/r9UKw9s/qb6s7jKyvwXSV6VQHkv1iVPOCxzL41y5JImW1YiePp2pZlbTby+7F12IPsM6ionsSxmwABbQIDAQAB
```

Dynect:
```
google._domainkey:
  type: TXT
  value: '"v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnvUZ3wn3GvTx413NLq0PViwC1w7TZubYyipPswsyECqii1xxmDtSZjSTWq2iYU3FBeyii6wNS4yl0JQ4kS286Sbe1LWCr7ovS5KTEZgu/gVK4A07nKKKXOjmTXuTMqwsTMnYCvwkhACANXzuhE3ArhChPEOFzhAF+2waLgQ8/pBPtEXG49g+aXjfwkbRmxmla"
    "vjQKwM9gQhEPL+drfU0CwQa4X/BVMq6JTcPW73UPZfQPtqjKbxW6hJQ1tOFLj2fV/lFL/r9UKw9s/qb6s7jKyvwXSV6VQHkv1iVPOCxzL41y5JImW1YiePp2pZlbTby+7F12IPsM6ionsSxmwABbQIDAQAB"'
```

Sync Output:
```
********************************************************************************
* example.com.
********************************************************************************
* dyn (DynProvider)
*   Update
*     <TxtRecord TXT 3600, google._domainkey.example.com., ['"v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnvUZ3wn3GvTx413NLq0PViwC1w7TZubYyipPswsyECqii1xxmDtSZjSTWq2iYU3FBeyii6wNS4yl0JQ4kS286Sbe1LWCr7ovS5KTEZgu/gVK4A07nKKKXOjmTXuTMqwsTMnYCvwkhACANXzuhE3ArhChPEOFzhAF+2waLgQ8/pBPtEXG49g+aXjfwkbRmxmla" "vjQKwM9gQhEPL+drfU0CwQa4X/BVMq6JTcPW73UPZfQPtqjKbxW6hJQ1tOFLj2fV/lFL/r9UKw9s/qb6s7jKyvwXSV6VQHkv1iVPOCxzL41y5JImW1YiePp2pZlbTby+7F12IPsM6ionsSxmwABbQIDAQAB"']> ->
*     <TxtRecord TXT 3600, google._domainkey.example.com., ['v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnvUZ3wn3GvTx413NLq0PViwC1w7TZubYyipPswsyECqii1xxmDtSZjSTWq2iYU3FBeyii6wNS4yl0JQ4kS286Sbe1LWCr7ovS5KTEZgu/gVK4A07nKKKXOjmTXuTMqwsTMnYCvwkhACANXzuhE3ArhChPEOFzhAF+2waLgQ8/pBPtEXG49g+aXjfwkbRmxmlavjQKwM9gQhEPL+drfU0CwQa4X/BVMq6JTcPW73UPZfQPtqjKbxW6hJQ1tOFLj2fV/lFL/r9UKw9s/qb6s7jKyvwXSV6VQHkv1iVPOCxzL41y5JImW1YiePp2pZlbTby+7F12IPsM6ionsSxmwABbQIDAQAB']> (config)
```

It seems to be a difference in NSOne's API inputs, versus their query outputs. They respond correctly when querying DNS directly, but their API shows differently.

I'm not sure what a solution would be for this, but it is definitely a provider specific issue. Do you think it would be handled in the NS1 (and maybe other) providers code in OctoDNS or somewhere else? As the Dynect + NSOne records are identical, but their API outputs are different
