### ISSUE TITLE
CNAME cannot coexist with other records spuriously?

### ISSUE THREAD

**Issue by wrouesnel** [github/octodns#145]
This type of construct in a zone seems to be rejected, but near as I can tell should be allowed?
```yaml
'*.github':
  ttl: 60
  type: CNAME
  value: github.zone
github:
  ttl: 60
  type: CNAME
  value: ghe-blue.prod.servers.zone
```

Basically: I have this config deployed in PowerDNS now and working but OctoDNS is rejecting it as invalid - I believe this is incorrect, as it's fairly undefined whether a wildcard like this also includes records before the * (testing shows "maybe").
