### ISSUE TITLE
SRV validation issue

### ISSUE THREAD

**Issue by o-be-one** [github/octodns#188]
Hello,

first of all, thanks a lot ross amd @vanbroup for your work on CloudFlare SRV records, i'm already using it ^^.

I have an issue with SRV validation. I've read in code that you have to fix things about it.
Validation check absolutely wants a "value" field (and, as integers, not unicode) so i just can't validate my SRV record. Here what i've put in my config file (without value field because it seems to be not required normally):
```
_myservice._tcp:
  port: 43166
  priority: 1
  target: myservice.mydomain.tld.
  ttl: 300
  type: SRV
  weight: 1
```

Edit: just seend that we are talking of validation for SRV here:
https://github.com/github/octodns/pull/185#issuecomment-363002451
But suggested to open an issue so, here you go :).

Thank you for your support!

**Comment by ross** [comment]
The SRV record type takes the following format when there's multiple values:

```yaml
_srv._tcp:
  ttl: 600
  type: SRV
  values:
  - port: 30
    priority: 10
    target: foo-1.githubtest.net.
    weight: 20
  - port: 30
    priority: 12
    target: foo-2.githubtest.net.
    weight: 20
```

As is the case for all of the multi-value record types if there's only one you can drop back to using just `value`.

```yaml
_srv._tcp:
  ttl: 600
  type: SRV
  value:
    port: 30
    priority: 12
    target: foo-2.githubtest.net.
    weight: 20
```
