### ISSUE TITLE
DNS Made Easy Provider: CAA value trimming issue

### ISSUE THREAD

**Issue by mpatenaude** [github/octodns#220]
Hello,

There is an issue handling the CAA record of the DNS ME API.  For example, applying the following CAA record:

```yaml
  - ttl: 86400
    type: CAA
    value:
      flags: 0
      tag: issue
      value: entrust.net
```
to an already properly configured zone would produce this change in error:

```
* dnsme (DnsMadeEasyProvider)
*   Update
*     <CaaRecord CAA 86400, example.com., ['0 issue "ntrust.ne"']> ->
*     <CaaRecord CAA 86400, example.com., ['0 issue "entrust.net"']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=10
```

Note that dumping that same zone actually create a bad configuration entry for the CAA record too.

**Fix:**

Removing the trimming from the following line fix the issue:

https://github.com/github/octodns/blob/87f8e0503b4d7252d49173f263f275488ce0e5e1/octodns/provider/dnsmadeeasy.py#L184

i.e. replacing `'value': record['value'][1:-1]` with simply `'value': record['value']`

Thanks.

**Comment by yzguy** [comment]
I am not seeing the same behavior. I also noticed that your example shows the record being updated from "ntrust.ne" to "entrust.net". Can you double check if your record is correct in the DNSMadeEasy Console/API?

YAML File:

```yaml
---
test:
  ttl: 86400
  type: CAA
  value:
    flags: 0
    tag: issue
    value: entrust.net
```

Noop:

```
********************************************************************************
* yzguy.io.
********************************************************************************
* dnsmadeeasy (DnsMadeEasyProvider)
*   Create <CaaRecord CAA 86400, test.yzguy.io., ['0 issue "entrust.net"']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```

Query after apply:

```
-> dig CAA test.yzguy.io @ns1.sandbox.dnsmadeeasy.com +short
0 issue "entrust.net"
```

Dumping the zone after adding the one record gives me a YAML file of

```yaml
---
test:
  ttl: 86400
  type: CAA
  value:
    flags: 0
    tag: issue
    value: entrust.net
```

**Comment by yzguy** [comment]
I was fiddling around to see if I could reproduce your output, with the following settings I was able to get it

- Name: test
- Provider: Other
- Type: issue
- Value: "ntrust.ne"
- Issuer Critical: 0
- TTL: 86400

Then perform a `noop`, I get the output just like yours

```
********************************************************************************
* yzguy.io.
********************************************************************************
* dnsmadeeasy (DnsMadeEasyProvider)
*   Update
*     <CaaRecord CAA 86400, test.yzguy.io., ['0 issue "ntrust.ne"']> ->
*     <CaaRecord CAA 86400, test.yzguy.io., ['0 issue "entrust.net"']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=1
********************************************************************************
```

And dumping it I get

```yaml
---
test:
  ttl: 86400
  type: CAA
  value:
    flags: 0
    tag: issue
    value: ntrust.ne
```

Please have a look and see if your record is accidentally configured as "ntrust.ne" for the Value. If it's correct then we'll have to look deeper.

**Comment by yzguy** [comment]
I tried a full Create, Noop Update, Dump and was unable to reproduce it trimming the value.

Input YAML:

```yaml
---
test:
  ttl: 86400
  type: CAA
  value:
    flags: 0
    tag: issue
    value: entrust.net
```

Noop for create:

```
********************************************************************************
* yzguy.io.
********************************************************************************
* dnsmadeeasy (DnsMadeEasyProvider)
*   Create <CaaRecord CAA 86400, test.yzguy.io., ['0 issue "entrust.net"']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```

Query after create:

```
-> dig CAA test.yzguy.io @ns1.sandbox.dnsmadeeasy.com +short
0 issue "entrust.net"
```

Noop Update:

```
********************************************************************************
* yzguy.io.
********************************************************************************
* dnsmadeeasy (DnsMadeEasyProvider)
*   Update
*     <CaaRecord CAA 86400, test.yzguy.io., ['0 issue "digicert.com"']> ->
*     <CaaRecord CAA 86400, test.yzguy.io., ['0 issue "entrust.net"']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=1
********************************************************************************
```

YAML Output after dump:

```
---
test:
  ttl: 86400
  type: CAA
  value:
    flags: 0
    tag: issue
    value: entrust.net
```

**Comment by mpatenaude** [comment]
Thanks for checking this out.  Note that I'm using the master branch.

This is against our production zone, and the CAA appears to be correct in the DNS ME UI and using dig:

```
dig @ns10.dnsmadeeasy.com. hopper.com CAA +short
0 issue "entrust.net"
```
and using the DNS ME Perl wrapper script to contact their API directly:

```
perl dnsmeapi.pl https://api.dnsmadeeasy.com/V2.0/dns/managed/${DOMAINID}/records -H accept:application/json | jq . | tee out

grep -B1 -A14 issue out
    {
      "caaType": "issue",
      "issuerCritical": 0,
      "source": 1,
      "ttl": 86400,
      "gtdLocation": "DEFAULT",
      "sourceId": <removed>,
      "failover": false,
      "monitor": false,
      "hardLink": false,
      "dynamicDns": false,
      "failed": false,
      "name": "",
      "value": "entrust.net",
      "id": 66158282,
      "type": "CAA"
    },
```

Dumping using:

```
octodns-dump --config-file=dnsme.yml --output-dir=tmp/ hopper.com. dnsme
...
```
And checking out the generated config file, you can see that it trimmed the first and last character.

```
grep -C5 CAA tmp/hopper.com.yaml
? ''
: - ttl: 86400
    type: A
    value: 64.254.233.20
  - ttl: 86400
    type: CAA
    value:
      flags: 0
      tag: issue
      value: ntrust.ne
  - ttl: 86400
```
I figure that using the dumped configuration and re-loading it will report no changes since during the "sync" check with DNS ME it does the same transform, i.e. receive `entrust.net` from DNS ME API, strips first and last chars then compare with the config that indeed contains `ntrust.ne`

i.e.
```
mv config/hopper.com.yaml config/hopper.com.yaml.bak
cp tmp/hopper.com.yaml config/
octodns-sync --config-file=dnsme.yml
...
2018-03-14T06:06:48  [139966477137728] INFO  DnsMadeEasyProvider[dnsme] plan:   No changes
2018-03-14T06:06:48  [139966477137728] INFO  Manager
********************************************************************************
No changes were planned
********************************************************************************
```

Manually modifying the configuration to have the proper `entrust.net`:

```
grep -C5 CAA config/hopper.com.yaml
? ''
: - ttl: 86400
    type: A
    value: 64.254.233.20
  - ttl: 86400
    type: CAA
    value:
      flags: 0
      tag: issue
      value: entrust.net
  - ttl: 86400
```
and re-checking produce:

```octodns-sync --config-file=dnsme.yml
...
2018-03-14T06:09:11  [140408541677376] INFO  Manager
********************************************************************************
* hopper.com.
********************************************************************************
* dnsme (DnsMadeEasyProvider)
*   Update
*     <CaaRecord CAA 86400, hopper.com., ['0 issue "ntrust.ne"']> ->
*     <CaaRecord CAA 86400, hopper.com., ['0 issue "entrust.net"']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=65
********************************************************************************
```

Now, if I just remove the "trimming" of the value in the provider:

```bash
vim /home/mathp/miniconda2/envs/public-dns/lib/python2.7/site-packages/octodns/provider/dnsmadeeasy.py
```

and checking with the same configuration, i.e. the last one with the full `entrust.net` entry:

```octodns-sync --config-file=dnsme.yml
...
2018-03-14T06:11:59  [140483360134976] INFO  Manager
********************************************************************************
No changes were planned
********************************************************************************```
```

I'm not certain why trimming is applied to the record value field in the code, was it to remove double quotes at some point, possibly?

```python
...
    def _data_for_CAA(self, _type, records):
        values = []
        for record in records:
            values.append({
                'flags': record['issuerCritical'],
                'tag': record['caaType'],
                'value': record['value'][1:-1]
...
