### ISSUE TITLE
Invalid IP Address

### ISSUE THREAD

**Issue by Parushgit** [github/octodns#278]
Hi, 

I am just trying to add a record in a zone file with ip Address in the key `value` and it always throws error `octodns.record.ValidationError: Invalid record   - invalid ip address "['172.20.35.226']"`. Although the IP address is valid.

Thanks!

**Comment by ross** [comment]
Can you drop the relevant yaml in here?

**Comment by Parushgit** [comment]
Sure! Thanks for your reply. 

Please find it [here](https://gist.github.com/Parushgit/99a744a29be70d7c80a8055d9caf862b).

**Comment by ross** [comment]
Ah. It's using the singular `value`, but has an array configured with `-`.  Either of the following should do the trick.

```yaml
api:
  ttl: 60
  type: A
  values:
    - 18.207.220.66
```

```yaml
api:
  ttl: 60
  type: A
  value: 18.207.220.66
```
