### ISSUE TITLE
Slash escaped semicolons showing up with literal slashes in DNSimple

### ISSUE THREAD

**Issue by MaxWofford** [github/octodns#296]
Escaping semicolons like so:
```yaml
_dmarc:
  ttl: 1
  type: TXT
  value: v=DMARC1\; p=none\; rua=mailto:dmarc_report@hackclub.com\; ruf=mailto:dmarc_report@hackclub.com\; fo=1
```
produces this on DNSimple:
![screenshot 2018-11-06 18 48 09](https://user-images.githubusercontent.com/5891442/48107450-86860500-e1f4-11e8-9462-285796edf90f.png)

```bash
maxwofford@breadfruit:~ $ dig +short TXT _dmarc.hackclub.com
"v=DMARC1\\; p=none\\; rua=mailto:dmarc_report@hackclub.com\\; ruf=mailto:dmarc_report@hackclub.com\\; fo=1"
```

Looks like DNSimple's API is literally interpreting the escape slashes octoDNS is sending
