### ISSUE TITLE
Using Include and Exclude 

### ISSUE THREAD

**Issue by dogsbody** [github/octodns#323]
Hi,

I would LOVE the ability to include a couple of records and excluding some records when copying a zone. I see that this seems to have been integrated in #111 however can't find any documentation on how to use it.

Can anyone point me in the right direction please?

This tool has already saved us hours of work.  Thank you :-)

**Comment by ross** [comment]
Best best is to look at the [unit test config bits that were added s part of that PR](https://github.com/github/octodns/pull/111/files#diff-75f067e7e7cc1ee8ee40891b6131c31a). Unfortunately there isn't any documentation on it at this point.

```yaml
included:
  octodns:
    included: 
      - other-id
  type: A
  value: 1.2.3.4
excluded:
  octodns:
    excluded:
      - provider-id
  type: A
  value: 1.2.3.4
```

The difference between the two is the default behavior. With `excluded` the specific provider ids provided will ignore the record. With `included` only the named providers will include the record. The provider id is the name given to the providers in your main config file.
