### ISSUE TITLE
Included/Excluded on Apex Records

### ISSUE THREAD

**Issue by brianeclow** [github/octodns#328]
How does one leverage `included` and `excluded` on the apex records? I just want to exclude one value from the array, due to Dyn provider not being able to configure/adjust the http-redirect service.

This is a follow up to #323

**Comment by brianeclow** [comment]
I figured it out.

```
---
? ''
: - octodns:
      excluded:
      - magicprovider
    ttl: 60
    type: A
    values:
    - 1.2.3.4
    - 5.6.7.8
  - type: MX
    values:
    - exchange: thing.example.com.
      preference: 10
  - type: TXT
    value: v=spf1 include:_spf.example.com -all
```
