### ISSUE TITLE
Route53: Dynamic record not being pushed

### ISSUE THREAD

**Issue by AppleMaster** [github/octodns#400]
I have the below configured as a record on a domain:
```
www:
  dynamic:
    pools:
      na:
        fallback: eu
        values:
        - value: aloadofELBstuffhere.amazonaws.com.
      eu:
        values:
        - value: vif07.example.com.
        - value: vif08.example.com.
    rules:
    - geos:
      - AF
      - EU
      pool: eu
    - geos:
      - NA
      - SA
      pool: na
    - pool: eu
  ttl: 300
  type: CNAME
  value: web.example.com.
```

When I run octodns-sync --doit, i get the below readout for this domain:

`*   Create <CnameRecord CNAME 300, www.example.com., web.example.com.> (config)`

As you can see, none of the information provided via the dynamic record is pushed with the sync. I would expect the pool/geo information to be pushed up into this record, as with the geo record type.
I cannot use the geo record type for this, as www has to be a CNAME in order to point to an AWS ELB resource - is there something obviously wrong with my configuration? (Copied from the documentation)?
