### ISSUE TITLE
Option to disable auto-created health checks for dynamic records

### ISSUE THREAD

**Issue by danhanks** [github/octodns#422]
I have a use case where I'd like to use dynamic records, but for which I don't want the healthchecks automatically created. Would it be possible to add an option to the config to disable the auto-creation of the health checks?

**Comment by ross** [comment]
> I have a use case where I'd like to use dynamic records, but for which I don't want the healthchecks automatically created.

Can you elaborate on your use case just to get it recorded down so that if/when someone goes to look at this they have an example to keep in mind?

It should be possible to do. There are some existing bits to customize health checks documented in https://github.com/github/octodns/blob/master/docs/dynamic_records.md#health-checks. Adding something like `disabled: true` should be doable, though off the top of my head I don't know how much that would change/impact the dynamic providers. 

This is a big enough task and not in our current usage of things that I probably won't get to it soon. Would welcome PRs.

**Comment by bazd** [comment]
I would also like to disable the health checks for dynamic records, as I have dns records that resolve to private addresses and these are not supported for health checks in Route 53

**Comment by ross** [comment]
> There are cases when I simply want to CNAME to another dynamic record which does its own health-checking and failover and I wouldn't want to health-check that dynamic record itself. I may also want to CNAME to a 3rd party load balancer (for eg [Citrix ITM](https://www.citrix.com/products/citrix-intelligent-traffic-management/)) which also has its own mechanism for health-checking and failover.

I've done this pretty frequently, but in those cases it's a simple CNAME pointed at a dynamic A. I wouldn't want 2 levels of targeting involved as it'd seem to get really complicated where traffic was directed. What's the setup leading to wanting 2 levels of targeting?

> (PS: This [current issue](https://github.com/octodns/octodns/issues/422) is for disabling health-check record wide, my use-case is per-pool, commenting here since it is a very similar request)

In general not opposed to optional health checking in general at the pool level, thought it's not something I've needed and thus haven't implemented. It'd be a bit of work to figure out the schema on the records/pools themselves and would require some research for each of the various dynamic providers to figure out the implementation details.

**Comment by meghashyamps** [comment]
Below are 2 illustration of why we need the option to have a monitor as "always up". 

1. (This is the nesting or 2 levels of targeting) The answer/answers are themselves dynamic records which are self managed. `as-rr` in the below example:
```
sample from test.com.yaml zone file
---
main:
  dynamic:
    pools:
      as-rr:
        values:
        - value: as-rr.test.com
      eu-rr:
        values:
        - value: eu-rr.test.com
    rules:
    - geos:
      - AS
      pool: as-rr
    - geos:
      - EU
      pool: eu-rr
    - pool: eu-rr
  ttl: 60
  type: CNAME
  values:
  - default-test.com
```

sample from test.com.yaml zone file
```
---
as-rr:
  dynamic:
    pools:
      rr:
        values:
        - value: as-rr1.test.com
          weight: 76
        - value: as-rr2.test.com
          weight: 80
        - value: as-rr3.test.com
          weight: 90
        - value: as-rr4.test.com
          weight: 36
        - value: as-rr5.test.com
          weight: 100
        - value: as-rr6.test.com
          weight: 136
        - value: as-rr7.test.com
          weight: 200
        - value: as-rr8.test.com
          weight: 170
    rules:
    - geos:
      - pool: rr
  ttl: 60
  type: CNAME
  values:
  - rr-test.com
```

Here we do not want to monitor `as-rr.test.com` itself but `as-rr.test.com` has monitors running for each of its children which should dictate how its answers are handed out. Of course, you could make a case that the pool `as-rr` and its contents can be replaced with direct IP addresses with their weights under `main.test.com`. But we have usages of `as-rr.test.com` in many other places, so replacing each of those occurrences with dynamic A's is too cumbersome to manage. Also imagine a case where if I have to change the weight for a single child answer (which happens frequently as we scale our infra up/down), I need to find and update in each of its occurrence in multiple places.

2. The answers are CNAME targets of 3rd party endpoints such as Citrix ITM / AWS global accelerator / Azure front door which don't need monitoring since they have their own monitors that is not managed by us

sample from test.com.yaml zone file
```
---
main:
  dynamic:
    pools:
      as-rr:
        values:
        - value: rum-based-answer.thirdparty.com
      eu-rr:
        values:
        - value: eu-rr.test.com
    rules:
    - geos:
      - AS
      pool: as-rr
    - geos:
      - EU
      pool: eu-rr
    - pool: eu-rr
  ttl: 60
  type: CNAME
  values:
  - default-test.com
```

This example is similar to the previous one, but the value for `as-rr` endpoint is not a dynamic record, but its a CNAME target for a 3rd party service such as Azure Front Door or Citrix ITM (RUM based steering). These are usually not self managed and they have their own monitors doing its keepalive work for us, so all customers have to do is CNAME to them. Even in this scenario, we would ideally set the monitor to "always serve" or "up" and leave the task of actual monitoring to the 3rd party.

**Comment by ross** [comment]
> Of course, you could make a case that the pool `as-rr` and its contents can be replaced with direct IP addresses with their weights under `main.test.com`.

Yeah that's what I'd expect to see.

> But we have usages of `as-rr.test.com` in many other places, so replacing each of those occurrences with dynamic A's is too cumbersome to manage.

Do you have cases where `as-rr.test.com.` is used without `eu-rr.test.com.` or with different targeting? I had a setup with a single/primary dynamic record with pools and all the values and targeting and then a bunch of static CNAMES pointed at that. 

```yaml
---
'':
  type: ALIAS
  value: service.example.com.
service:
  # full dynamic record with pools and values here
  ...
'whatever':
  type: CNAME
  value: service.example.com.
www:
  type: CNAME
  value: service.example.com.
```

> 1. The answers are CNAME targets of 3rd party endpoints such as Citrix ITM / AWS global accelerator / Azure front door which don't need monitoring since they have their own monitors that is not managed by us

This is closer to the use-cases I've seen for dynamic CNAMES, though I've always still wanted healthchecking and failover. E.g. if you send users in the US to AWS and EU to Azure for whatever reason and say that Azure has a major outage in the EU and things are hard down. Wouldn't you prefer to have users fallback to AWS in the US?

Anyway, as said above I'm open to non-healthchecked stuff, just think it isn't something that will be super common and may  often be a :foot: :gun: :grin:
