### ISSUE TITLE
Convert from TravisCI to GitHub Action

### ISSUE THREAD

**Issue by yzguy** [github/octodns#425]
Just got around to watching the GitHub Universe keynotes which got me pretty interested in playing around with Actions.

Wondering if it would be worth it to swap to GitHub Actions for OctoDNS and away from TravisCI. 

I'd imagine the workflow would look similar to

```yaml
name: OctoDNS
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7]
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install virtualenv
      - name: CI Build
        run: |
          ./script/cibuild
```
