### ISSUE TITLE
Record Sorting Requirements

### ISSUE THREAD

**Issue by clwells** [github/octodns#43]
Am attempting to load a large zone and keep getting:

```
yaml.constructor.ConstructorError: keys out of order: ab, a
```

I've debugged it down to the ordering of the records in the YAML input file.  The following provides the error:

```yaml
---
ab:
    type: A
    values: [1.1.1.1]
a:
    type: A
    values: [2.2.2.2]
```

What sorting standard should the YAML keys be treated with before being fed to OctoDNS?

**Comment by ross** [comment]
It requires things to be sorted alphabetically, so the `a` record should come before `ab`.  Same goes for the 2nd level, though in this cases they're already ordered correctly. 

It's just something that we try to enforce to keep things from getting messy over time. It's nice to be able to scan to the right spot in a file and know whether or not something is there. It's also nice to have a consistent/standard way to order the record fields. It could be made optional so that it can be turned off if people don't wan it, but without someone feeling strongly enough to do the PR it'll probably remain as is.

**Comment by clwells** [comment]
It doesn't appear strictly alphabetical.  This is the result of a PHP "natural" sort. I've tried a few sort ordering variations and haven't been able to match what's expected yet:

```yaml
---
45a03129:
    ttl: 14400
    type: A
    values: [1.1.1.1]
45a0392a:
    ttl: 14400
    type: A
    values: [2.2.2.2]
```

```
yaml.constructor.ConstructorError: keys out of order: 45a03129, 45a0392a
```
