### ISSUE TITLE
Assigning multiple zones to the same zone file

### ISSUE THREAD

**Issue by jleroy** [github/octodns#591]
I have a lot of domains who uses the same zone file. Is the a way to link a bunch of domains to a zone without adding an entry under `zones` for each domain?

I'm thinking of something like this:
```
zones:
  example.com.:
  sources:
    - config
  targets:
    - dnsimple
  zones:
    - example.net.
    - example.org.
```

**Comment by yzguy** [comment]
You could create symlinks on the filesystem.

```
example.net.yaml -> example.com.
example.org.yaml -> example.com.
```

**Comment by brianeclow** [comment]
I wrote a sorting script that pulls in the octoDNS sort and yaml formatting. Which when you run against this type of configuration, starting with

```
# Arbitary hash in config
zoneconfig: &zoneconfig
  sources:
    - config
  targets:
    - dnsimple

zones:
 example.com.:
   <<: *zoneconfig
 example.net.:
   <<: *zoneconfig
```

results in

```
# Arbitary hash in config
zoneconfig:
  sources: &id001
    - config
  targets: &id002
    - dnsimple

zones:
 example.com.:
  sources: *id001
  targets: *id002
 example.net.:
  sources: *id001
  targets: *id002
```
