### ISSUE TITLE
CNAME support in GeoIP 

### ISSUE THREAD

**Issue by vanbroup** [github/octodns#62]
I have the following config, www (A) and www3 (AAAA) are created but www2 (CNAME) is ignored as [described in the documentation](https://github.com/github/octodns/blob/master/docs/records.md#geodns-support).

```
www:
  geo:
    AS:
      - 1.1.1.1
    AS-JP:
      - 3.3.3.3
    EU:
      - 2.2.2.2
    EU-NL:
      - 5.5.5.5
    NA-US-CA:
      - 4.4.4.4
  ttl: 300
  type: A
  value: 1.2.3.4
www2:
  geo:
    AP:
      - cdn.asia.
    EU:
      - cdn.eu.
    JP:
      - cdn.jp.
    NA-US-CA:
      - cdn.com.
    NL:
      - cdn.nl.
  ttl: 300
  type: CNAME
  value: cdn.net.
www3:
  geo:
    AS:
      - 2001:DB8::2
    AS-JP:
      - 2001:DB8::3
    EU:
      - 2001:DB8::4
    EU-NL:
      - 2001:DB8::5
    NA-US-CA:
      - 2001:DB8::6
  ttl: 300
  type: AAAA
  value: 2001:DB8::1
```
Route53:
![image](https://user-images.githubusercontent.com/722070/26975279-63b951fa-4d1f-11e7-9a74-bfdac49f0c4a.png)

Same for Dyn.

**Comment by ross** [comment]
Geo support was only added to `A` & `AAAA` records as those were the types that had specific use cases, I was able to dig into and figure out exactly how they should work, and test. Without having the geo support the `geo` section is just ignored in general. 

We have `CNAME`s pointed to geo `A`/`AAAA` that we own and we have `CNAME`s pointed to `A`/`AAAA` that external providers own and do anycast/geo with. In your example above are you pointing to different cdn providers in different regions or just different endpoints for the same company?

Adding `CNAME` should look relatively similar to `A`/`AAAA`. The biggest difference is going to be that it's single-value rather than multi-values so it's not trivial. The other part that wasn't immediately clear is what health-checking should look like on a `CNAME` geo record. I can't see any reason why the same checks wouldn't make sense, but without having a specific use case laid out it's hard to evaluate.

**Comment by vanbroup** [comment]
You are right, my example is showing a simple region based CDN selection. This should be quite simple to implement.

The real use case is a bit more complicated. We would like to support load-balancing and health-checking but instead of a set of A/AAAA records, we return one CNAME of one of the external CDN providers (as they don't allow you to use direct addresses). 

In Route53 this can be done via Latency-Based Routing or Weighted Sets, the Dyn Traffic Director also uses a Weight in combination with Serve Count and for NS1 the filter chain provides many more options.

**Comment by Pushpendra3d** [comment]
The main thing you want is to get the record as CNAME instead of other type(A/AAAA) of records. Right?

**Comment by vanbroup** [comment]
Yes the initial goal is that this configuration snippet would work:

```
www2:
  geo:
    AP:
      - cdn.asia.
    EU:
      - cdn.eu.
    JP:
      - cdn.jp.
    NA-US-CA:
      - cdn.com.
    NL:
      - cdn.nl.
  ttl: 300
  type: CNAME
  value: cdn.net.
```

Eventually, I would like something like below that would load balance three CDN's for the AP region, two for the EU region and a single or more for the rest. We need to use weighted sets as you can only return one CNAME record in a response according to the standard. The DNS provider would return a record based on the location and weight, the next query would get the next record for the same location and weight.

```
www3:
  geo:
    AP:
      - cdn.asia.:
           weight: 10
      - asia-cdn.com.
           weight: 10
      - asia2-cdn.com.
           weight: 20
    EU:
      - cdn.eu.
      - eu-cdn.com.
    JP:
      - cdn.jp.
    NA-US-CA:
      - cdn.com.
    NL:
      - cdn.nl.
  ttl: 300
  type: CNAME
  values: 
      - cdn.net.
      - cdn.asia.
      - cdn.eu.
      - cdn.com.
```
