### ISSUE TITLE
example.com.yaml Order of entries

### ISSUE THREAD

**Issue by NicolaiSchmid** [github/octodns#64]
In my example.com.yaml file, I have quite a few subdomains which I would like to group into logical blocks with comments. But every time I change the order to be not alphabetically the software throws an error that the entries are out of order.
Is there a way to structure the entries the way I desire or is it a design requirement to have those in order?
Thanks for Your help!

**Comment by NicolaiSchmid** [comment]
No, I was talking about the ordering of the subdomains.
```
cloud:
  ttl: 1
  type: CNAME
  value: 1.2.3.4
```
hast to appear before
```
zolo:
  ttl: 1
  type: CNAME
  value: 1.2.3.4
```
