### ISSUE TITLE
Clean pattern for sharing record values across multiple names

### ISSUE THREAD

**Issue by ross** [github/octodns#7]
Could either be implemented in `YamlProvider` or potentially use make use of yaml features like [this](http://stackoverflow.com/a/8466243) or [this](http://stackoverflow.com/a/9197237). 

I'd probably lean towards the yaml route as it has some pretty powerful feautres, but we'd have to make sure that they work well with PyYaml and document a suggested way to do them.

If implemented in `YamlProvider` and not yaml it could potentially look something like:

```yaml
---
_octodns:
  templates:
    www
      type: A
      values:
        - 1.2.3.4
        - 1.2.3.5
      geo:
        NA-US-CA:
          - 2.2.3.4
          - 2.2.3.5
'':
  _template: www
'www':
  _template: www
```

**Comment by vanbroup** [comment]
Are there any further plans to implement a template logic like this?

It would be great to have per zone and global (per config) templates that can be used across zones. For example really useful for configurations where you have several resources hosted under a CDN and want to be able to stir traffic based on GeoIP.

```yaml
_octodns:
  templates:
    cdn
      type: CNAME
      values:
        - customer.cdn.com.
        - customer.anothercdn.com.
        - @.fqdn-prefixed-cdn.com.
      geo:
        NA-US-CA:
          - customer.cdn.com.
        EU:
          - customer.anothercdn.com.
        AP:
        - @.fqdn-prefixed-cdn.com.
```

Where:
`        - @.fqdn-prefixed-cdn.com.`

Would be translated by OctoDNS to:
`        - www.domain.com.fqdn-prefixed-cdn.com.`
