### ISSUE TITLE
Documentation for Adding PTR records

### ISSUE THREAD

**Issue by multco-troy** [github/octodns#919]
I'm unable to find documentation regarding adding PTR records.  Do I need to create new Zone files for each reverse zone?  My source is config and target is route53.

**Comment by yzguy** [comment]
Hello,

A reverse zone is essentially the same as a forward zone except the naming and the records within it. 

```
# config.yaml

zones:
  2.0.192.in-addr.arpa.:
    sources:
      - config
    targets:
      - route53
```

Your YAML would look like

```
# 2.0.192.in-addr.arpa.yaml
? ''
: type: NS
  values:
  - ns1.example.net.
  - ns2.example.net.
'1':
  type: PTR
  value: host1.example.net.
'2':
  type: PTR
  value: host2.example.net.
```
