### ISSUE TITLE
Route53 Using roles Instead of access keys

### ISSUE THREAD

**Issue by jr-RXcode** [github/octodns#94]
Is it possible to incorporate using ec2 roles instead of the aws Access keys. Most of our environment uses roles instead of access keys. Can this feature be added ?
Thanks!

**Comment by yzguy** [comment]
I'll take a peek at this. There will be things added in the Route53 provider so you can specify what kind of auth you're going to use, then it can look for the appropriate values, and for backwards compatibility have Access Key ID + Secret Access Key be default.

Something like

```
route53:
    class: octodns.provider.route53.Route53Provider
    auth_method: env_vars
    access_key_id: AKAABC123
    secret_access_key: SAK123131
```

```
route53:
    class: octodns.provider.route53.Route53Provider
    auth_method: credential_file
    credential_path: ~/.aws/credentials
    profile: default
```

```
route53:
    class: octodns.provider.route53.Route53Provider
    auth_method: assume_role
    role_arn: arn:aws:iam:...
    access_key_id: AKAABC123
    secret_access_key: SAK123131
    ...
```

Are you assuming IAM Roles directly or via EC2 with an IAM role configured?

**Comment by yzguy** [comment]
@ross Was thinking about this one, so right now it's kinda of explicit on the authentication method. A simple way would be just detect if access_key_id and secret_access_key are set, if they aren't just create a normal client, and let boto3 do the work of figuring out the authentication per http://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials

This would then make OctoDNS work with any authentication method supported by boto3 instantly, support environment variables, shared credentials file, assume_role, etc.

On the other hand, you could key off the `auth_method` or have maybe an `auth` hash

```
auth:
  method: env_vars
  access_key_id: AKAABC123
  secret_access_key: SAK123131
```

```
auth:
  method: shared_credentials_file
  credentials_path: ~/.aws/credentials
  profile: default
```

Then in the Route53 Provider, you can call a method like `_r53_client` and pass this hash, and then based off the contents figure out what to feed the boto3 client to make the correct one.

```
    def r53_client(self, auth, config):
        if auth['method'] == 'env_vars':
            return client('route53', aws_access_key_id=auth['aws_access_key_id'],
                    aws_secret_access_key=auth['aws_secret_access_key'],
                    config)
        elif auth['method'] == 'shared_credentials_file':
            session = Session(profile_name=auth['profile_name'])
            return
        elif auth['method'] == 'assume_role':
            ...
```

Little bit of a "explicit versus implicit" thing to decide.

**Comment by ross** [comment]
That seems reasonable. The logic behind it being explicit was so that there's a path to be able to use multiple accounts within a single config/run. That wasn't really an option when letting boto do the auth config dynamically. 

I'd be fine with allowing it to be more flexible in terms of how things auth so long as the existing behavior is allowed/preserved so that if you do the following it continues to look things up and explicitly configure the client with them.

```yaml
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/OCTODNS_AWS_ACCESS_KEY_ID
    secret_access_key: env/OCTODNS_AWS_SECRET_ACCESS_KEY
```
